# Site settings
title: WRITING PAD
email: 
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://pangdouya.github.io"
url: "http://pangdouya.github.io"

# Build settings
markdown: kramdown
permalink: pretty
